name: Rust build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build release
      run: cargo build --release --verbose

    - name: Upload release binary
      uses: actions/upload-artifact@v3
      with:
        name: rust-release-binary
        path: target/release/my_binary_name
