name: Rust build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libwayland-dev libasound2-dev pkg-config

    - name: Build release
      run: cargo build --release --verbose

    - name: Upload release binary
      uses: actions/upload-artifact@v4
      with:
        name: rust-release-binary
        path: target/release/firefly
